name: Scheduled check and build on dependency updates

permissions:
  contents: write
  pull-requests: write
  actions: write

on:
  schedule:
    # Run Hourly
    - cron: '0 * * * *'
  workflow_dispatch:
  
jobs:
  check_release:
    runs-on: ubuntu-latest
    name: Hourly check for dependency updates

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
      with:
        egress-policy: audit

    - name: Checkout this repo
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup git
      run: |
          git config --global user.email "gh@ctsubm.it"
          git config --global user.name "ctsubmit"

    - name: Run dev_update_dependencies.sh
      run: chmod +x dev_update_dependencies.sh; ./dev_update_dependencies.sh

    - name: Check for changes
      id: check_changes
      run: |
        git fetch origin main
        if [[ $(git diff --name-only origin/main) ]]; then
          echo "One or more files have changed"
          echo "dev_files_changed=true" >> $GITHUB_OUTPUT
        else
          echo "No files have changed"
          echo "dev_files_changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request
      if: steps.check_changes.outputs.dev_files_changed == 'true'
      uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
      with:
        add-paths: |
          dev_go.*
          pki/data/optimal_parents.csv
        token: ${{ secrets.GITHUB_TOKEN }}
        base: main
        branch: auto-dev-update
        title: "Dependency Update"
        body: "This pull request was automatically created due to a dependency update."
        commit-message: Dependency update

    - name: Auto-Merge PR
      if: steps.check_changes.outputs.dev_files_changed == 'true'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          gh pr merge auto-dev-update -d -m

    - name: Trigger Dev Container Build
      if: steps.check_changes.outputs.dev_files_changed == 'true'
      run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/crtsh/ctsubmit/actions/workflows/docker-dev.yml/dispatches \
        -d '{"ref":"main"}'
